name: Lint

on: [push, pull_request]

jobs:
  build:
    if: github.repository == 'orangehrm/oxd'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install
      - name: Lint
        run: yarn workspace oxd-components lint
